version: "2"
services:
  node:
    image: "node:12"
    user: "node"
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports:
      - "5000:5000"
    command: "npm run start:dev"
  mysql:
    image: mysql:5.7
    ports:
      - "6000:3306"
    volumes:
        - "./mysql-data:/var/lib/mysql"
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_USER: root
        MYSQL_PASSWORD: root
        MYSQL_DATABASE: books_catalogue